import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {useEffect, useState} from "react";
import Link from "next/link"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [urlTime, setUrlTime] = useState(true)
    const [days, setDays] = useState(0)
    const [hours,setHours] = useState(0)
    const [minutes,setMinutes] = useState(0)
    const [seconds,setSeconds] = useState(0)



    useEffect(() => {
        const target = new Date("01/02/2023 23:59:59")
        const interval = setInterval(() => {
            const now = new Date()
            const difference = target.getTime() - now.getTime()

            const days = Math.floor(difference/ (1000 * 60 * 60 * 24))
            setDays(days)

            const hours = Math.floor((difference%(1000 * 60 * 60 * 24))/(1000*60*60))
            setHours(hours)

            const minutes = Math.floor((difference%(1000*60*60))/(1000*60))
            setMinutes(minutes)

            const seconds = Math.floor((difference%(1000*60))/1000)
            setSeconds(seconds)
        }, 1000)

        return () =>  clearInterval(interval)
    },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <div className='timer-wrapper'>
         <div className="timer-inner"></div>
         <div className="timer-segment">
             <span className="time">{days}</span>
             <span className="label">Days</span>
         </div>
         <div className="timer-segment">
             <span className="time">{hours}</span>
             <span className="label">Hours</span>
         </div>
         <div className="timer-segment">
             <span className="time">{minutes}</span>
             <span className="label">Minutes</span>
         </div>
         <div className="timer-segment">
             <span className="time">{seconds}</span>
             <span className="label">Seconds</span>
         </div>
         { urlTime ? (
             <div>
                 <Link href="https://github.com/yollcumerve" legacyBehavior>
                     <a>
                         <button disabled={seconds>0 || seconds<0}>Go to GİTHUB</button>
                     </a>
                 </Link>
             </div>
         ): null}

     </div>
    </>
  )
}
